name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
      tag:
        description: "Revision"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login (GitHub)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./src/${{ inputs.name }}
          file: ./src/${{ inputs.name }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.name }}-${{ inputs.tag }}
